language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules

install:
  - npm install

services:
  - mysql

before_script:
  - mysql -e 'DROP DATABASE IF EXISTS turing_test;'
  - mysql -e 'CREATE DATABASE turing_test;'

script:
  - npm test

after_success:
- npm run coverage

after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
